apiVersion: v1
data:
  application.yaml: |-
    camel:
      servlet:
        mapping:
          enabled: true
          context-path: /*
      lra:
        enabled: true
        coordinator-url: http://lra-coordinator:8080
        coordinator-context-path: /lra-coordinator    
        local-participant-url: http://create-loan:8080
        local-participant-context-path: /lra-participant
      service:
        lra.enabled: true
      dataformat:
        json-jackson:
          auto-discover-object-mapper: true    
    saga-demo:
      loan:
        create:
          endpoint: "http://loan-service:8080/createloan"
        delete:
          endpoint: "http://loan-service:8080/deleteloan"
      applicant:
        update-limit:
          endpoint: "http://applicant-service:8080/updateloanlimit"
      saga:
        route:
          endpoint: "http://create-loan:8080/saga/route"
    # Logger configuration
    logging:
      pattern:
        console: "%d %-5level %logger : %msg%n"
      level:
        org.springframework: info
        org.springframework.security: debug
    # server configuration
    server:
      port: 8080
kind: ConfigMap
metadata:
  name: create-loan
  namespace: saga-loan-demo
