apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: loan-demo-database
  namespace: saga-loan-demo
stringData:
  database-name: loan-demo-database
  database-password: postgres
  database-user: postgres
  database-data: /temp/data/pgdata
