apiVersion: v1
data:
  application.yaml: |-
    spring:
      profiles:
        active: development
      application:
        name: "loanmodel"
      datasource:
        url:  jdbc:postgresql://loan-demo-database:5432/sagademo?currentSchema=sagademo
        username: sagademo
        password: sagademo
      jpa:
        hibernate:
          ddl-auto: none
          naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        database: POSTGRESQL
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        open-in-view: false
        generate-ddl: true
    # Logger configuration
    logging:
      pattern:
        console: "%d %-5level %logger : %msg%n"
      level:
        org.springframework: info
        org.hibernate: debug
        org.springframework.security: debug
    # Server configuration
    server:
      port: 8080
      servlet:
        context-path: /
kind: ConfigMap
metadata:
  name: loan-demo-model
  namespace: saga-loan-demo
